apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: gcr.io/flask-k8s-lab/flask-app:v1  # ✅ Đường dẫn đầy đủ tới GCR
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
