name: Build and Deploy to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: flask-cluster
  GKE_ZONE: asia-southeast1-a
  DEPLOYMENT_NAME: flask-app

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}
    
    - name: Configure Docker
      run: gcloud auth configure-docker --quiet
    
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          gcr.io/${{ env.PROJECT_ID }}/flask-app:${{ github.sha }}
          gcr.io/${{ env.PROJECT_ID }}/flask-app:latest
    
    - name: Configure kubectl
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
    
    - name: Deploy to GKE
      run: |
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} flask=gcr.io/${{ env.PROJECT_ID }}/flask-app:${{ github.sha }}
        kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}