name: Build and Deploy to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: flask-cluster
  GKE_ZONE: asia-southeast1-a
  DEPLOYMENT_NAME: flask-app

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure Docker
      run: gcloud auth configure-docker --quiet
      
    - name: Build Docker image
      run: docker build -t gcr.io/$PROJECT_ID/flask-app:$GITHUB_SHA .
      
    - name: Push to GCR
      run: |
        echo ${{ secrets.GKE_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
        docker push gcr.io/$PROJECT_ID/flask-app:$GITHUB_SHA
        
    - name: Configure kubectl
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: $GKE_CLUSTER
        location: $GKE_ZONE
        credentials: ${{ secrets.GKE_SA_KEY }}
        
    - name: Deploy
      run: |
        kubectl set image deployment/$DEPLOYMENT_NAME flask=gcr.io/$PROJECT_ID/flask-app:$GITHUB_SHA
        kubectl rollout status deployment/$DEPLOYMENT_NAME